apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: rails-blog
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "false"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: rails-blog
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/berinle/rails_blog.git
      ref:
        branch: main
